language: ruby
dist: trusty
rvm: 2.4.2

import:
  - travis-ci/build-configs/db-setup.yml

cache:
  bundler: true

services:
- redis
- rabbitmq

env:
  matrix:
  - RAKE_TASK=spec
  global:
    secure: BdVC3OHqYcgePLrkKIk28Ewn/dxCYFf3Cx+Q8P+BCDj6UPJyRSbKmILBzuX96H5xhKmUFo0A/upUhJI9UUP9aXHO7MzRe04/c88QdO4wGacVUaIyB20S0pr262zbc/nA50K9cVgpmWc64n6uQR1tgM6ZyyBnBeXkLzCAOHPq99I=

before_install: gem install bundler

script: bundle exec rspec spec

jobs:
 include:
   - stage: "testing time"
   - stage: ":ship: it to Quay.io"
     sudo: required
     dist: trusty
     ruby:
     services:
     addons:
     before_install: skip
     install: skip
     before_script:
       - curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > ./docker-compose
       - sudo mv ./docker-compose /usr/local/bin/docker-compose
       - sudo chmod +x /usr/local/bin/docker-compose
     script: ./script/docker-build-and-push
