language: ruby

rvm: 2.4.2

import:
  - travis-ci/build-configs:db-setup.yml

cache:
  bundler: true

services:
- redis
- rabbitmq

env:
  matrix:
  - RAKE_TASK=spec
  global:
    secure: BdVC3OHqYcgePLrkKIk28Ewn/dxCYFf3Cx+Q8P+BCDj6UPJyRSbKmILBzuX96H5xhKmUFo0A/upUhJI9UUP9aXHO7MzRe04/c88QdO4wGacVUaIyB20S0pr262zbc/nA50K9cVgpmWc64n6uQR1tgM6ZyyBnBeXkLzCAOHPq99I=

before_install: gem install bundler

jobs:
 include:
   - stage: "testing time"
     script: bundle exec rspec spec
   - stage: ":ship: it to quay.io"
     ruby:
     services:
     addons:
     before_install: skip
     install: skip
     script: make ship
     if: type = cron OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
